import 'dart:async';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:ndu_project/providers/project_data_provider.dart';
import 'package:ndu_project/screens/launch_checklist_screen.dart';
import 'package:ndu_project/screens/scope_completion_screen.dart';
import 'package:ndu_project/services/execution_phase_service.dart';
import 'package:ndu_project/utils/execution_phase_ai_seed.dart';
import 'package:ndu_project/widgets/execution_phase_ui.dart';
import 'package:ndu_project/widgets/kaz_ai_chat_bubble.dart';
import 'package:ndu_project/widgets/launch_editable_section.dart';
import 'package:ndu_project/widgets/launch_phase_navigation.dart';
import 'package:ndu_project/widgets/responsive.dart';
import 'package:ndu_project/widgets/responsive_scaffold.dart';

class RiskTrackingWorkspaceScreen extends StatefulWidget {
  const RiskTrackingWorkspaceScreen({super.key});

  static void open(BuildContext context) {
    Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => const RiskTrackingWorkspaceScreen()),
    );
  }

  @override
  State<RiskTrackingWorkspaceScreen> createState() =>
      _RiskTrackingWorkspaceScreenState();
}

class _RiskTrackingWorkspaceScreenState
    extends State<RiskTrackingWorkspaceScreen> {
  final Set<String> _selectedFilters = {'All risks'};
  final List<_RiskItem> _risks = [];
  final List<_SimpleNote> _signals = [];
  final List<_SimpleNote> _plans = [];
  bool _loading = true;
  bool _isGenerating = false;
  bool _autoGenerated = false;
  Timer? _saveDebounce;

  String? get _projectId {
    try {
      return ProjectDataInherited.maybeOf(context)?.projectData.projectId;
    } catch (_) {
      return null;
    }
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) => _loadData());
  }

  @override
  void dispose() {
    _saveDebounce?.cancel();
    super.dispose();
  }

  Future<void> _loadData() async {
    final projectId = _projectId;
    if (projectId == null || projectId.isEmpty) {
      if (mounted) setState(() => _loading = false);
      return;
    }
    try {
      final snapshot = await ExecutionPhaseService.loadRiskTrackingSnapshot(
        projectId: projectId,
      );

      if (!mounted) return;
      setState(() {
        _risks
          ..clear()
          ..addAll(((snapshot['riskItems'] as List?) ?? const [])
              .map((item) => _RiskItem.fromMap(Map<String, dynamic>.from(item))));
        _signals
          ..clear()
          ..addAll(((snapshot['riskSignals'] as List?) ?? const [])
              .map((item) => _SimpleNote.fromMap(Map<String, dynamic>.from(item))));
        _plans
          ..clear()
          ..addAll(((snapshot['mitigationPlans'] as List?) ?? const [])
              .map((item) => _SimpleNote.fromMap(Map<String, dynamic>.from(item))));
        _loading = false;
      });

      await _autoGenerateIfNeeded();
    } catch (e) {
      debugPrint('Error loading risk tracking snapshot: $e');
      if (mounted) setState(() => _loading = false);
    }
  }

  Future<void> _autoGenerateIfNeeded() async {
    if (_autoGenerated || _isGenerating) return;
    if (_risks.isNotEmpty || _signals.isNotEmpty || _plans.isNotEmpty) return;
    _autoGenerated = true;
    await _addAiDrafts(replaceExisting: true);
  }

  Future<void> _addAiDrafts({bool replaceExisting = false}) async {
    if (_isGenerating) return;
    setState(() => _isGenerating = true);
    try {
      final generated = await ExecutionPhaseAiSeed.generateEntries(
        context: context,
        section: 'Risk Tracking',
        sections: const {
          'risks': 'Execution risks to monitor',
          'signals': 'Risk signals and alerts',
          'mitigationPlans': 'Mitigation plans and ownership',
        },
        itemsPerSection: 3,
      );

      if (!mounted) return;
      setState(() {
        if (replaceExisting) _risks.clear();
        _risks.addAll((generated['risks'] ?? const <LaunchEntry>[]).map(
          (entry) => _RiskItem(
            id: DateTime.now().microsecondsSinceEpoch.toString(),
            title: entry.title,
            owner: 'Risk Owner',
            probability: 'Medium',
            impact: 'Medium',
            status: entry.status?.isNotEmpty == true ? entry.status! : 'Open',
            nextReview: 'TBD',
          ),
        ));
        if (replaceExisting) _signals.clear();
        _signals.addAll((generated['signals'] ?? const <LaunchEntry>[])
            .map((entry) => _SimpleNote(entry.title, entry.details)));
        if (replaceExisting) _plans.clear();
        _plans.addAll((generated['mitigationPlans'] ?? const <LaunchEntry>[])
            .map((entry) => _SimpleNote(entry.title, entry.details)));
      });
      _persist();
    } catch (e) {
      debugPrint('Risk AI generation failed: $e');
    } finally {
      if (mounted) setState(() => _isGenerating = false);
    }
  }

  void _persist() {
    final projectId = _projectId;
    if (projectId == null || projectId.isEmpty) return;
    _saveDebounce?.cancel();
    _saveDebounce = Timer(const Duration(milliseconds: 600), () async {
      await ExecutionPhaseService.saveRiskTrackingSnapshot(
        projectId: projectId,
        riskItems: _risks.map((item) => item.toMap()).toList(),
        riskSignals: _signals.map((item) => item.toMap()).toList(),
        mitigationPlans: _plans.map((item) => item.toMap()).toList(),
        userId: FirebaseAuth.instance.currentUser?.uid,
      );
    });
  }

  List<_RiskItem> get _filteredRisks {
    if (_selectedFilters.contains('All risks')) return _risks;
    return _risks.where((risk) {
      if (_selectedFilters.contains('High impact')) {
        return risk.impact == 'High' || risk.impact == 'Critical';
      }
      if (_selectedFilters.contains('Needs review')) {
        return risk.status == 'Open' || risk.status == 'At Risk';
      }
      if (_selectedFilters.contains('Blocked')) return risk.status == 'Blocked';
      return true;
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    final isNarrow = MediaQuery.sizeOf(context).width < 980;
    return ResponsiveScaffold(
      activeItemLabel: 'Risk Tracking',
      backgroundColor: const Color(0xFFF5F7FB),
      body: Stack(
        children: [
          SingleChildScrollView(
            padding: EdgeInsets.all(AppBreakpoints.pagePadding(context)),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if (_loading) const LinearProgressIndicator(minHeight: 2),
                if (_loading) const SizedBox(height: 16),
                _buildHeader(),
                const SizedBox(height: 20),
                Wrap(
                  spacing: 10,
                  runSpacing: 10,
                  children: const ['All risks', 'High impact', 'Needs review', 'Blocked']
                      .map((filter) => ChoiceChip(
                            label: Text(filter),
                            selected: _selectedFilters.contains(filter),
                            onSelected: (_) {
                              setState(() {
                                _selectedFilters
                                  ..clear()
                                  ..add(filter);
                              });
                            },
                            showCheckmark: false,
                          ))
                      .toList(),
                ),
                const SizedBox(height: 20),
                ExecutionMetricsGrid(
                  metrics: [
                    ExecutionMetricData(label: 'Active risks', value: _risks.length.toString(), icon: Icons.warning_amber_outlined, emphasisColor: const Color(0xFFEF4444)),
                    ExecutionMetricData(label: 'High impact', value: _risks.where((risk) => risk.impact == 'High' || risk.impact == 'Critical').length.toString(), icon: Icons.priority_high_outlined, emphasisColor: const Color(0xFFF97316)),
                    ExecutionMetricData(label: 'Needs review', value: _risks.where((risk) => risk.status == 'Open' || risk.status == 'At Risk').length.toString(), icon: Icons.event_note_outlined, emphasisColor: const Color(0xFF2563EB)),
                    ExecutionMetricData(label: 'Mitigation notes', value: _plans.length.toString(), icon: Icons.shield_outlined, emphasisColor: const Color(0xFF10B981)),
                  ],
                ),
                const SizedBox(height: 24),
                _buildRegister(isNarrow),
                const SizedBox(height: 20),
                if (isNarrow) ...[
                  _buildNotePanel('Risk signals', 'Alerts and watchpoints from the field.', _signals),
                  const SizedBox(height: 20),
                  _buildNotePanel('Mitigation notes', 'Working mitigation direction and ownership context.', _plans),
                ] else
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Expanded(child: _buildNotePanel('Risk signals', 'Alerts and watchpoints from the field.', _signals)),
                      const SizedBox(width: 20),
                      Expanded(child: _buildNotePanel('Mitigation notes', 'Working mitigation direction and ownership context.', _plans)),
                    ],
                  ),
                const SizedBox(height: 24),
                LaunchPhaseNavigation(
                  backLabel: 'Back: Start-up / Launch Checklist',
                  nextLabel: 'Next: Scope Completion',
                  onBack: () => LaunchChecklistScreen.open(context),
                  onNext: () => ScopeCompletionScreen.open(context),
                ),
                const SizedBox(height: 48),
              ],
            ),
          ),
          const KazAiChatBubble(),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return ExecutionPageHeader(
      badge: 'Execution Safety',
      title: 'Risk Tracking Workspace',
      description: 'A persistent, editable execution risk register with AI draft support and responsive views.',
      trailing: ExecutionActionBar(
        actions: [
          ExecutionActionItem(label: 'Add risk', icon: Icons.add, tone: ExecutionActionTone.primary, onPressed: _showRiskEditor),
          ExecutionActionItem(label: 'Add AI draft', icon: Icons.auto_awesome_outlined, tone: ExecutionActionTone.ai, onPressed: _addAiDrafts, isLoading: _isGenerating),
        ],
      ),
    );
  }

  Widget _buildRegister(bool isNarrow) {
    return ExecutionPanelShell(
      title: 'Risk register',
      subtitle: 'Track owner, severity, status, and next review.',
      child: _filteredRisks.isEmpty
          ? const ExecutionEmptyState(icon: Icons.warning_amber_outlined, title: 'No risks yet', description: 'Add a risk manually or use AI to draft the initial register.')
          : isNarrow
              ? Column(children: _filteredRisks.map((risk) => _RiskCard(risk: risk, onEdit: () => _showRiskEditor(existing: risk), onDelete: () => _deleteRisk(risk))).toList())
              : SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: DataTable(
                    headingRowColor: WidgetStateProperty.all(const Color(0xFFF8FAFC)),
                    columns: const [
                      DataColumn(label: Text('Risk')),
                      DataColumn(label: Text('Owner')),
                      DataColumn(label: Text('Probability')),
                      DataColumn(label: Text('Impact')),
                      DataColumn(label: Text('Status')),
                      DataColumn(label: Text('Next review')),
                      DataColumn(label: Text('Actions')),
                    ],
                    rows: _filteredRisks.map((risk) => DataRow(cells: [
                          DataCell(SizedBox(width: 260, child: Text(risk.title, style: const TextStyle(fontWeight: FontWeight.w700)))),
                          DataCell(Text(risk.owner)),
                          DataCell(ExecutionStatusBadge(label: risk.probability)),
                          DataCell(ExecutionStatusBadge(label: risk.impact)),
                          DataCell(ExecutionStatusBadge(label: risk.status)),
                          DataCell(Text(risk.nextReview)),
                          DataCell(Row(mainAxisSize: MainAxisSize.min, children: [
                            IconButton(onPressed: () => _showRiskEditor(existing: risk), icon: const Icon(Icons.edit_outlined, size: 18)),
                            IconButton(onPressed: () => _deleteRisk(risk), icon: const Icon(Icons.delete_outline, size: 18)),
                          ])),
                        ])).toList(),
                  ),
                ),
    );
  }

  Widget _buildNotePanel(String title, String subtitle, List<_SimpleNote> items) {
    return ExecutionPanelShell(
      title: title,
      subtitle: subtitle,
      child: items.isEmpty
          ? const ExecutionEmptyState(icon: Icons.notes_outlined, title: 'No notes yet', description: 'AI-generated and team-authored notes will appear here.')
          : Column(
              children: items.map((item) => Container(
                width: double.infinity,
                margin: const EdgeInsets.only(bottom: 12),
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(color: const Color(0xFFF8FAFC), borderRadius: BorderRadius.circular(18), border: Border.all(color: const Color(0xFFE2E8F0))),
                child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                  Text(item.title, style: const TextStyle(fontWeight: FontWeight.w800)),
                  if (item.details.isNotEmpty) ...[
                    const SizedBox(height: 8),
                    Text(item.details, style: const TextStyle(fontSize: 13, color: Color(0xFF475569), height: 1.45)),
                  ],
                ]),
              )).toList(),
            ),
    );
  }

  Future<void> _showRiskEditor({_RiskItem? existing}) async {
    final titleController = TextEditingController(text: existing?.title ?? '');
    final ownerController = TextEditingController(text: existing?.owner ?? '');
    final nextReviewController = TextEditingController(text: existing?.nextReview ?? '');
    final formKey = GlobalKey<FormState>();
    String probability = existing?.probability ?? 'Medium';
    String impact = existing?.impact ?? 'Medium';
    String status = existing?.status ?? 'Open';

    final updated = await showExecutionEditorSheet<_RiskItem>(
      context: context,
      title: existing == null ? 'Add risk' : 'Edit risk',
      icon: Icons.warning_amber_outlined,
      child: StatefulBuilder(
        builder: (context, setModalState) => Form(
          key: formKey,
          child: Column(children: [
            TextFormField(controller: titleController, decoration: const InputDecoration(labelText: 'Risk title'), validator: (value) => value == null || value.trim().isEmpty ? 'Enter a risk title' : null),
            const SizedBox(height: 16),
            TextFormField(controller: ownerController, decoration: const InputDecoration(labelText: 'Owner')),
            const SizedBox(height: 16),
            DropdownButtonFormField<String>(initialValue: probability, items: const ['Low', 'Medium', 'High'].map((value) => DropdownMenuItem(value: value, child: Text(value))).toList(), onChanged: (value) { if (value != null) setModalState(() => probability = value); }, decoration: const InputDecoration(labelText: 'Probability')),
            const SizedBox(height: 16),
            DropdownButtonFormField<String>(initialValue: impact, items: const ['Low', 'Medium', 'High', 'Critical'].map((value) => DropdownMenuItem(value: value, child: Text(value))).toList(), onChanged: (value) { if (value != null) setModalState(() => impact = value); }, decoration: const InputDecoration(labelText: 'Impact')),
            const SizedBox(height: 16),
            DropdownButtonFormField<String>(initialValue: status, items: const ['Open', 'At Risk', 'Blocked', 'Closed'].map((value) => DropdownMenuItem(value: value, child: Text(value))).toList(), onChanged: (value) { if (value != null) setModalState(() => status = value); }, decoration: const InputDecoration(labelText: 'Status')),
            const SizedBox(height: 16),
            TextFormField(controller: nextReviewController, decoration: const InputDecoration(labelText: 'Next review')),
          ]),
        ),
      ),
      actions: [
        OutlinedButton(onPressed: () => Navigator.of(context).pop(), child: const Text('Cancel')),
        FilledButton(
          onPressed: () {
            if (!(formKey.currentState?.validate() ?? false)) return;
            Navigator.of(context).pop(_RiskItem(id: existing?.id ?? DateTime.now().microsecondsSinceEpoch.toString(), title: titleController.text.trim(), owner: ownerController.text.trim().isEmpty ? 'Unassigned' : ownerController.text.trim(), probability: probability, impact: impact, status: status, nextReview: nextReviewController.text.trim().isEmpty ? 'TBD' : nextReviewController.text.trim()));
          },
          child: Text(existing == null ? 'Add risk' : 'Save changes'),
        ),
      ],
    );

    titleController.dispose();
    ownerController.dispose();
    nextReviewController.dispose();

    if (updated == null || !mounted) return;
    setState(() {
      final index = _risks.indexWhere((risk) => risk.id == updated.id);
      if (index == -1) {
        _risks.insert(0, updated);
      } else {
        _risks[index] = updated;
      }
    });
    _persist();
  }

  void _deleteRisk(_RiskItem risk) {
    setState(() => _risks.removeWhere((item) => item.id == risk.id));
    _persist();
  }
}

class _RiskCard extends StatelessWidget {
  const _RiskCard({required this.risk, required this.onEdit, required this.onDelete});
  final _RiskItem risk;
  final VoidCallback onEdit;
  final VoidCallback onDelete;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(18), border: Border.all(color: const Color(0xFFE5E7EB))),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          Expanded(child: Text(risk.title, style: const TextStyle(fontWeight: FontWeight.w800))),
          IconButton(onPressed: onEdit, icon: const Icon(Icons.edit_outlined, size: 18)),
          IconButton(onPressed: onDelete, icon: const Icon(Icons.delete_outline, size: 18)),
        ]),
        const SizedBox(height: 10),
        Wrap(spacing: 8, runSpacing: 8, children: [
          ExecutionStatusBadge(label: risk.probability),
          ExecutionStatusBadge(label: risk.impact),
          ExecutionStatusBadge(label: risk.status),
        ]),
        const SizedBox(height: 10),
        Text('Owner: ${risk.owner} · Next review: ${risk.nextReview}', style: const TextStyle(fontSize: 12, color: Color(0xFF64748B), fontWeight: FontWeight.w600)),
      ]),
    );
  }
}

class _RiskItem {
  const _RiskItem({required this.id, required this.title, required this.owner, required this.probability, required this.impact, required this.status, required this.nextReview});
  final String id;
  final String title;
  final String owner;
  final String probability;
  final String impact;
  final String status;
  final String nextReview;
  Map<String, dynamic> toMap() => {'id': id, 'title': title, 'owner': owner, 'probability': probability, 'impact': impact, 'status': status, 'nextReview': nextReview};
  factory _RiskItem.fromMap(Map<String, dynamic> map) => _RiskItem(id: map['id']?.toString() ?? '', title: map['title']?.toString() ?? '', owner: map['owner']?.toString() ?? 'Unassigned', probability: map['probability']?.toString() ?? 'Medium', impact: map['impact']?.toString() ?? 'Medium', status: map['status']?.toString() ?? 'Open', nextReview: map['nextReview']?.toString() ?? 'TBD');
}

class _SimpleNote {
  const _SimpleNote(this.title, this.details);
  final String title;
  final String details;
  Map<String, dynamic> toMap() => {'title': title, 'details': details};
  factory _SimpleNote.fromMap(Map<String, dynamic> map) => _SimpleNote(map['title']?.toString() ?? '', map['details']?.toString() ?? '');
}
